name: kualiva_merchant_mb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    path: ^1.9.0
    path_provider: ^2.1.4
    intl: ^0.19.0
    permission_handler: ^11.3.1
    easy_localization: ^3.0.7
    page_transition: ^2.1.0
    flutter_launcher_icons: ^0.14.1
    adaptive_theme: ^3.6.0
    outline_gradient_button: ^2.0.1+1
    cached_network_image: ^3.4.1
    flutter_svg: ^2.0.10+1
    device_info_plus: ^11.0.0
    curved_navigation_bar: ^1.0.6
    carousel_slider: ^5.0.0
    url_launcher: ^6.3.1
    flutter_image_compress: ^2.3.0
    image_picker: ^1.1.2
    photo_view: ^0.15.0
    faker: ^2.2.0
    video_player: ^2.9.2
    motion: ^2.0.1
    bounce: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0


flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/kualiva_icon.png"

flutter:
    uses-material-design: true
    assets:
        - assets/videos/
        - assets/images/
        - assets/translation/
    fonts:
        - family: K2D
          fonts:
              - asset: assets/fonts/K2D-Regular.ttf
                weight: 400
              - asset: assets/fonts/K2D-Bold.ttf
                weight: 700
              - asset: assets/fonts/K2D-Italic.ttf
                style: italic